version: '3'
services:
  frontend:
    build: ./
    ports:
      - 8080:8080
  backend:
    build: ./src/backend
    ports:
      - 8000:8000
    environment:
      - GITHUB_TOKEN
volumes:
  backend: